name: 'Playwright Tests for Web Reader via BrowserStack'
on:
  schedule:
    - cron: '00 12 * * 1-5' # every day at 7-9 AM ET (12 PM wherever the server is) excluding weekends
jobs:
  test:
    name: 'Playwright Tests for Web Reader via BrowserStack'
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project-name: DRB Web Reader
          build-name: DRB Web Reader Automated Tests

      - name: 'BrowserStack Local Tunnel Setup' # set up tunnel connection between GitHub Actions runner environment and BrowserStack device cloud
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests on BrowserStack
        id: run-tests
        run: npx browserstack-node-sdk playwright test
        continue-on-error: true

      - name: Set failure workflow status 🚨
        if: steps.run-tests.outcome != 'success'
        run: exit 1

      - name: Set successful workflow status ✅
        if: steps.run-tests.outcome == 'success'
        run: exit 0
