name: 'Playwright Tests for Web Reader via BrowserStack'
on:
  schedule:
    - cron: '00 14 * * 1-5' # every day at 9-10 AM ET (2 PM wherever the server is) excluding weekends
  # push:
  #   branches: [main]
  pull_request: # remove when this GHA works
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: 'Playwright Tests for Web Reader via BrowserStack'
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username: clarissarichard_A7mus1
          access-key: Mj8NqLbtk74Y8yCShzPm

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests on BrowserStack
        id: run-tests
        run: npx browserstack-node-sdk playwright test html-reader-settings.spec.ts
        #continue-on-error: true

      - name: Set failure workflow status 🚨
        if: steps.run-tests.outcome != 'success'
        run: exit 1

      - name: Set successful workflow status ✅
        if: steps.run-tests.outcome == 'success'
        run: exit 0
