name: Playwright Tests for Web Reader
on:
  schedule:
    - cron: '00 14 * * 1-5' # every day at 9-10 AM ET (2 PM wherever the server is) excluding weekends
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build app and run tests
        id: run-tests
        run: |
          npm run test:ci:integration > output.txt
          cat output.txt
        continue-on-error: true

      # - name: Save test results to output
      #   id: test-results
      #   run: |
      #     echo "The test run had 5 failed tests and 2 flaky tests overall" > output.txt
      #     cat output.txt

      - name: Extract text between keywords (more robust)
        id: extract
        run: |
          output=$(cat output.txt)
            
          # For multiline content, use a different delimiter
          extracted=$(echo "$output" | perl -n -e '/failed(.*?)flaky/ && print $1')
            
          echo "Extracted text: '$extracted'"
          echo "extracted<<EOF" >> $GITHUB_OUTPUT
          echo "$extracted" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Use extracted text
        run: |
          echo "The text between those words is: ${{ steps.extract.outputs.extracted }}"

      - name: Set successful workflow status ✅
        if: steps.run-tests.outcome == 'success'
        run: exit 0

      - name: Set failure workflow status 🚨
        if: steps.run-tests.outcome != 'success'
        run: echo 'steps.run-tests.outcome' && exit 1

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: test_reports
          SLACK_MESSAGE: See "Build app and run tests" step in ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_TITLE: Web Reader Playwright Test Results
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: nyplorgBot
